/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan_barang;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daulah
 */
public class fpenjualan extends javax.swing.JFrame {

    public long total;
    public long bayar;
    public long kembali;
    public Statement st;
    Connection cn = koneksi.getKoneksi();

    private DefaultTableModel model;

    /**
     * Creates new form fpenjualan
     */
    public fpenjualan() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel();

        tbpenjualan.setModel(model);
        model.addColumn("ID");
        model.addColumn("kode barang");
        model.addColumn("nama barang");
        model.addColumn("harga satuan");
        model.addColumn("jumlah beli");
        model.addColumn("harga");
        loadData();
        nofaktur();
        tampilpilih();
    }

    public void FilterHuruf(KeyEvent a) {
        if (Character.isDigit(a.getKeyChar())) {
            a.consume();
            JOptionPane.showMessageDialog(null, "masukan huruf saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void FilterAngka(KeyEvent a) {
        if (Character.isAlphabetic(a.getKeyChar())) {
            a.consume();
            JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public final void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            String sql = "SELECT * FROM tbl_hitung_jual";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[6];
                o[0] = r.getString("id_hitung");
                o[1] = r.getString("kode_barang");
                o[2] = r.getString("nama_barang");
                o[3] = r.getString("hsatuan");
                o[4] = r.getString("jumlah_jual");
                o[5] = r.getString("harga");

                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }

    private void tampilpilih() {
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            String sql = "SELECT nama_barang FROM tbl_barang WHERE jumlah_barang !='0'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                cb_barang.addItem(r.getString("nama_barang"));
            }

            r.last();
            int jumlahdata = r.getRow();
            r.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void nofaktur() {
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            String sql = "SELECT * FROM tbl_penjualan ORDER by nofaktur desc";
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("nofaktur").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

                txt_nofaktur.setText("F" + Nol + AN);
            } else {
                txt_nofaktur.setText("F0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_nofaktur = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cb_barang = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txt_kodebarang1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_hargasatuan1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_jumlahjual1 = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpenjualan = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_cetak = new javax.swing.JButton();
        btn_total = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txt_kembalian = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        btn_selesai = new javax.swing.JButton();
        rp = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        nfaktur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_back2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setText("No. Faktur");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 41, 130, -1));

        txt_nofaktur.setBackground(new java.awt.Color(108, 122, 137));
        txt_nofaktur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nofaktur.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(txt_nofaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 42, 194, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setText("Nama Barang");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 83, 130, -1));

        cb_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang" }));
        cb_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_barangActionPerformed(evt);
            }
        });
        jPanel2.add(cb_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 83, 194, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(236, 240, 241));
        jLabel22.setText("Kode Barang");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 123, 130, -1));

        txt_kodebarang1.setBackground(new java.awt.Color(108, 122, 137));
        txt_kodebarang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_kodebarang1.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(txt_kodebarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 123, 194, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(236, 240, 241));
        jLabel23.setText("Harga Satuan");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 164, 130, -1));

        txt_hargasatuan1.setBackground(new java.awt.Color(108, 122, 137));
        txt_hargasatuan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_hargasatuan1.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(txt_hargasatuan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 164, 194, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(236, 240, 241));
        jLabel24.setText("Jumlah Jual");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 205, 130, -1));

        txt_jumlahjual1.setBackground(new java.awt.Color(108, 122, 137));
        txt_jumlahjual1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_jumlahjual1.setForeground(new java.awt.Color(228, 241, 254));
        txt_jumlahjual1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlahjual1KeyTyped(evt);
            }
        });
        jPanel2.add(txt_jumlahjual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 205, 194, -1));

        txt_total.setBackground(new java.awt.Color(108, 122, 137));
        txt_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_total.setForeground(new java.awt.Color(228, 241, 254));
        jPanel2.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 246, 162, 40));

        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 246, 194, 40));

        tbpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpenjualan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 365, 517, 317));

        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel2.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 309, 368, 38));

        jPanel3.setBackground(java.awt.Color.lightGray);

        btn_cetak.setText("CETAK");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btn_total.setText("TOTAL");
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Kembalian");

        txt_kembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Bayar");

        txt_bayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_bayarKeyTyped(evt);
            }
        });

        btn_selesai.setText("SELESAI TRANSAKSI");
        btn_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selesaiActionPerformed(evt);
            }
        });

        rp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rp.setText("Rp.");

        tot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txt_bayar)
                            .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 246, -1, -1));

        jumlah.setBackground(new java.awt.Color(108, 122, 137));
        jumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlah.setForeground(new java.awt.Color(228, 241, 254));
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        jPanel2.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 50, 10));
        jPanel2.add(nfaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Penjualan");

        btn_back2.setBackground(new java.awt.Color(242, 38, 19));
        btn_back2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_back2.setForeground(new java.awt.Color(255, 255, 255));
        btn_back2.setText("Back");
        btn_back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back2ActionPerformed
        fmenu fb = new fmenu();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_back2ActionPerformed

    private void cb_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_barangActionPerformed
        if (cb_barang.getSelectedItem().equals("pilih barang")) {
            txt_kodebarang1.setText("");
            txt_hargasatuan1.setText("");
        } else {
            try {
                Connection c = koneksi.getKoneksi();
                Statement s = c.createStatement();

                String sql = "SELECT kode_barang, jumlah_barang FROM tbl_barang WHERE nama_barang ='" + cb_barang.getSelectedItem() + "'";
                ResultSet r = s.executeQuery(sql);

                while (r.next()) {
                    txt_kodebarang1.setText(r.getString("kode_barang"));
                    jumlah.setText(r.getString("jumlah_barang"));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            try {
                Connection c = koneksi.getKoneksi();
                Statement s = c.createStatement();

                String sql = "SELECT harga_jual FROM tbl_barang WHERE nama_barang ='" + cb_barang.getSelectedItem() + "'";
                ResultSet r = s.executeQuery(sql);

                while (r.next()) {
                    txt_hargasatuan1.setText(r.getString("harga_jual"));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_cb_barangActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        if (txt_nofaktur.getText().equals("")
                || txt_kodebarang1.getText().equals("")
                || cb_barang.getSelectedItem().equals("")
                || txt_hargasatuan1.getText().equals("")
                || txt_jumlahjual1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);

        } else {
            String a = txt_jumlahjual1.getText();
            int aa = Integer.parseInt(a);

            String b = txt_jumlahjual1.getText();
            int bb = Integer.parseInt(b);
            if (aa > bb) {
                JOptionPane.showMessageDialog(null, "jumlah melebihi stok", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);
                txt_jumlahjual1.setText("");
            } else {

                if (txt_jumlahjual1.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "ISI JUMLAH BELI !");
                } else {
                    int jumlah, harga, total;

                    jumlah = Integer.parseInt(txt_jumlahjual1.getText().toString());
                    harga = Integer.parseInt(txt_hargasatuan1.getText().toString());
                    total = jumlah * harga;

                    txt_total.setText(Integer.toString(total));

                }
            }
        }
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        if (txt_nofaktur.getText().equals("")
                || txt_kodebarang1.getText().equals("")
                || cb_barang.getSelectedItem().equals("")
                || txt_hargasatuan1.getText().equals("")
                || txt_jumlahjual1.getText().equals("")
                || txt_total.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);

        } else {
            String kdbarangg = txt_kodebarang1.getText();
            String pilihbarangg = (String) cb_barang.getSelectedItem();
            String hsatuann = txt_hargasatuan1.getText();
            String tjumlahh = txt_jumlahjual1.getText();
            String totall = txt_total.getText();

            try {
                Connection c = koneksi.getKoneksi();

                String sql = "INSERT INTO tbl_hitung_jual VALUES (?, ?, ?, ?, ?, ?)";

                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, null);
                p.setString(2, kdbarangg);
                p.setString(3, pilihbarangg);
                p.setString(4, hsatuann);
                p.setString(5, tjumlahh);
                p.setString(6, totall);

                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println("Terjadi Error");
            } finally {
                nofaktur();
                txt_kodebarang1.setText("");
                cb_barang.setSelectedItem("");
                txt_hargasatuan1.setText("");
                txt_jumlahjual1.setText("");
                txt_total.setText("");
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);
                loadData();

            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void tbpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpenjualanMouseClicked
        int jawaban;
        if ((jawaban = JOptionPane.showConfirmDialog(null, "Yakin batal?", "Konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            try {

                int i = tbpenjualan.getSelectedRow();
                if (i == -1) {
                    return;
                }
                String id = (String) model.getValueAt(i, 0);

                st = cn.createStatement();
                st.executeUpdate("delete from tbl_hitung_jual where id_hitung = '" + id + "'");

                nofaktur();
                loadData();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tbpenjualanMouseClicked

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT SUM(`harga`) AS total FROM tbl_hitung_jual";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                tot.setText(r.getString("" + "total"));

            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }//GEN-LAST:event_btn_totalActionPerformed

    private void btn_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selesaiActionPerformed
        if (txt_bayar.getText().equals("") || txt_kembalian.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String a = txt_kembalian.getText();
            int ab = Integer.parseInt(a);
            if (ab < 0) {
                JOptionPane.showMessageDialog(null, "Uang anda kurang", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);
                txt_bayar.setText("");
                txt_kembalian.setText("");
            } else {
                try ( Connection c = koneksi.getKoneksi()) {
                    Statement s = c.createStatement();
                    String sql = "SELECT * FROM tbl_hitung_jual";
                    ResultSet r = s.executeQuery(sql);

                    while (r.next()) {
                        long millis = System.currentTimeMillis();
                        java.sql.Date date = new java.sql.Date(millis);
                        System.out.println(date);
                        String tgl = date.toString();
                        String sqla = "INSERT INTO tbl_penjualan VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

                        try ( PreparedStatement p = c.prepareStatement(sqla)) {
                            p.setString(1, txt_nofaktur.getText());
                            p.setString(2, r.getString("kode_barang"));
                            p.setString(3, r.getString("nama_barang"));
                            p.setString(4, r.getString("hsatuan"));
                            p.setString(5, r.getString("jumlah_jual"));
                            p.setString(6, r.getString("harga"));
                            p.setString(7, txt_bayar.getText());
                            p.setString(8, txt_kembalian.getText());
                            p.setString(9, tgl);

                            p.executeUpdate();
                        }
                    }
                    r.close();
                    s.close();

                    try ( PreparedStatement pst = c.prepareStatement("TRUNCATE `tbl_hitung_jual`")) {
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "TRANSAKSI SELESAI", "PT PRABU", JOptionPane.INFORMATION_MESSAGE);
                        loadData();
                        nfaktur.setText(txt_nofaktur.getText());
                        txt_bayar.setText("");
                        txt_kembalian.setText("");
                        tot.setText("");
                        nofaktur();
                        btn_cetak.setEnabled(true);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }

                } catch (SQLException e) {
                    System.out.println("Terjadi Error: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_selesaiActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        try {
            Desktop.getDesktop().browse(new URL("http://localhost/laporanpenjualan/invoice.php?lap&fk=" + nfaktur.getText() + "").toURI());
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyTyped
        FilterAngka(evt);
    }//GEN-LAST:event_txt_bayarKeyTyped

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        bayar = Integer.parseInt(String.valueOf(txt_bayar.getText()));
        total = Integer.parseInt(String.valueOf(tot.getText()));
        kembali = bayar - total;

        txt_kembalian.setText(Long.toString(kembali));
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void txt_jumlahjual1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahjual1KeyTyped
        FilterAngka(evt);
    }//GEN-LAST:event_txt_jumlahjual1KeyTyped

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fpenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back2;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_selesai;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_total;
    private javax.swing.JComboBox<String> cb_barang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nfaktur;
    private javax.swing.JLabel rp;
    private javax.swing.JTable tbpenjualan;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_hargasatuan1;
    private javax.swing.JTextField txt_jumlahjual1;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_kodebarang1;
    private javax.swing.JTextField txt_nofaktur;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
